spring:
  application:
    name: rabbit-stream-consumer
  cloud:
    stream:
      function:
        definition: personsInputChannel;othersInputChannel;allInputChannel
      defaultBinder: rabbit
      bindings:
        personsInputChannel-in-0:
          destination: persons-topic
          group: group1
          consumer:
            concurrency: 5
        othersInputChannel-in-0:
          destination: persons-topic
          group: group2
          consumer:
            concurrency: 5
        allInputChannel-in-0:
          destination: persons-topic
          group: group3
          consumer:
            concurrency: 5
      rabbit:
        bindings:
          personsInputChannel-in-0:
            consumer:
              durableSubscription: false
              autoBindDlq: true
              republishToDlq: false
              requeueRejected: true
              maxAttempts: 3
              transacted: true
              durable: false
              bindingRoutingKey: first.*.key,third.*.key
              bindingRoutingKeyDelimiter: ','
          othersInputChannel-in-0:
            consumer:
              durableSubscription: false
              autoBindDlq: true
              republishToDlq: false
              requeueRejected: true
              maxAttempts: 3
              transacted: true
              durable: false
              bindingRoutingKey: second.*.key
          allInputChannel-in-0:
            consumer:
              durableSubscription: false
              autoBindDlq: true
              republishToDlq: false
              requeueRejected: true
              maxAttempts: 3
              transacted: true
              durable: false
              bindingRoutingKey: "*.*.key"
  rabbitmq:
    broker-url: tcp://127.0.0.1:5672
    username: myuser
    password: mypass
    host: localhost
